"""add selected_seat_uuid to booking model

Revision ID: 037efc334fd1
Revises: cb1916e730bb
Create Date: 2026-08-20 10:35:17.406127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037efc334fd1'
down_revision: Union[str, Sequence[str], None] = 'cb1916e730bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
