"""add booking_uuid to selected seats

Revision ID: 0aa15739a112
Revises: e56ceee089ec
Create Date: 2026-08-20 11:23:29.159724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa15739a112'
down_revision: Union[str, Sequence[str], None] = 'e56ceee089ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_selected_seat_uuid_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'selected_seat_uuid')
    op.add_column('selected_seats', sa.Column('booking_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'selected_seats', 'bookings', ['booking_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selected_seats', type_='foreignkey')
    op.drop_column('selected_seats', 'booking_uuid')
    op.add_column('bookings', sa.Column('selected_seat_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bookings_selected_seat_uuid_fkey'), 'bookings', 'selected_seats', ['selected_seat_uuid'], ['uuid'])
    # ### end Alembic commands ###
