"""add route model to env

Revision ID: 0c03dd6397a0
Revises: 4504823eb134
Create Date: 2026-08-18 11:34:20.141189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c03dd6397a0'
down_revision: Union[str, Sequence[str], None] = '4504823eb134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('leaving_time', sa.Time(), nullable=False),
    sa.Column('destination_time', sa.Time(), nullable=False),
    sa.Column('with_ac', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('leaving_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
