"""add unique keys to name for location & bus number for bus

Revision ID: 3aa40a20a9cf
Revises: f375645bc299
Create Date: 2026-08-20 16:06:56.755492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa40a20a9cf'
down_revision: Union[str, Sequence[str], None] = 'f375645bc299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buses', ['bus_number'])
    op.create_unique_constraint(None, 'locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'buses', type_='unique')
    # ### end Alembic commands ###
