"""resolved issue in selected seat model

Revision ID: 493fb0f0bc70
Revises: 189562c3840f
Create Date: 2026-08-21 14:43:10.001725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493fb0f0bc70'
down_revision: Union[str, Sequence[str], None] = '189562c3840f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('selected_seats_seat_uuid_fkey'), 'selected_seats', type_='foreignkey')
    op.drop_constraint(op.f('selected_seats_route_uuid_fkey'), 'selected_seats', type_='foreignkey')
    op.create_foreign_key(None, 'selected_seats', 'seats', ['seat_uuid'], ['uuid'])
    op.create_foreign_key(None, 'selected_seats', 'routes', ['route_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selected_seats', type_='foreignkey')
    op.drop_constraint(None, 'selected_seats', type_='foreignkey')
    op.create_foreign_key(op.f('selected_seats_route_uuid_fkey'), 'selected_seats', 'buses', ['route_uuid'], ['uuid'])
    op.create_foreign_key(op.f('selected_seats_seat_uuid_fkey'), 'selected_seats', 'buses', ['seat_uuid'], ['uuid'])
    # ### end Alembic commands ###
