"""drop route uuid in route model

Revision ID: 521343b427d4
Revises: 5e494dfbf32b
Create Date: 2026-08-19 16:21:03.514221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521343b427d4'
down_revision: Union[str, Sequence[str], None] = '5e494dfbf32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('routes_route_uuid_fkey'), 'routes', type_='foreignkey')
    op.drop_column('routes', 'route_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('routes_route_uuid_fkey'), 'routes', 'routes', ['route_uuid'], ['uuid'])
    # ### end Alembic commands ###
