"""remove route_uuid from seat model

Revision ID: 5e494dfbf32b
Revises: e1a1584ee887
Create Date: 2026-08-19 15:49:11.618616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e494dfbf32b'
down_revision: Union[str, Sequence[str], None] = 'e1a1584ee887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('seats_route_uuid_fkey'), 'seats', type_='foreignkey')
    op.drop_column('seats', 'route_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('route_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('seats_route_uuid_fkey'), 'seats', 'routes', ['route_uuid'], ['uuid'])
    # ### end Alembic commands ###
