"""update routes & seats

Revision ID: 7c3d984dc882
Revises: e309b4239308
Create Date: 2026-08-18 16:49:54.305759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3d984dc882'
down_revision: Union[str, Sequence[str], None] = 'e309b4239308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('leaving_time', sa.Time(), nullable=False),
    sa.Column('destination_time', sa.Time(), nullable=False),
    sa.Column('with_ac', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_uuid', sa.UUID(), nullable=False),
    sa.Column('destination_uuid', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('leaving_date', sa.Date(), nullable=False),
    sa.Column('route_uuid', sa.UUID(), nullable=False),
    sa.Column('bus_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bus_uuid'], ['buses.uuid'], ),
    sa.ForeignKeyConstraint(['destination_uuid'], ['locations.uuid'], ),
    sa.ForeignKeyConstraint(['location_uuid'], ['locations.uuid'], ),
    sa.ForeignKeyConstraint(['route_uuid'], ['routes.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
