"""add constraint on selected seat per route

Revision ID: 92b034cdfb0d
Revises: 493fb0f0bc70
Create Date: 2026-08-24 12:46:51.619102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b034cdfb0d'
down_revision: Union[str, Sequence[str], None] = '493fb0f0bc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_selected_seat_route', 'selected_seats', ['route_uuid', 'seat_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_selected_seat_route', 'selected_seats', type_='unique')
    # ### end Alembic commands ###
