"""drop is_available in seats model

Revision ID: cb1916e730bb
Revises: 521343b427d4
Create Date: 2026-08-19 16:39:10.640106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1916e730bb'
down_revision: Union[str, Sequence[str], None] = '521343b427d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('with_ac', sa.Boolean(), nullable=False))
    op.drop_column('routes', 'with_ac')
    op.drop_column('seats', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('with_ac', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('buses', 'with_ac')
    # ### end Alembic commands ###
