"""add price to luggages and status to bookings

Revision ID: d1c0aa3c104c
Revises: 3aa40a20a9cf
Create Date: 2026-08-21 13:57:16.286127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c0aa3c104c'
down_revision: Union[str, Sequence[str], None] = '3aa40a20a9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('luggages', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luggages', 'price')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
