"""add seats

Revision ID: e1a1584ee887
Revises: 7c3d984dc882
Create Date: 2026-08-19 14:52:11.188438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a1584ee887'
down_revision: Union[str, Sequence[str], None] = '7c3d984dc882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('route_uuid', sa.UUID(), nullable=False),
    sa.Column('bus_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bus_uuid'], ['buses.uuid'], ),
    sa.ForeignKeyConstraint(['route_uuid'], ['routes.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
