"""add booking, luggage, selectedSeat model to the .env

Revision ID: e56ceee089ec
Revises: 037efc334fd1
Create Date: 2026-08-20 10:59:07.429137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56ceee089ec'
down_revision: Union[str, Sequence[str], None] = '037efc334fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('luggages',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('number_of_luggages', sa.Integer(), nullable=False),
    sa.Column('weight_of_luggages', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('selected_seats',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('seat_uuid', sa.UUID(), nullable=False),
    sa.Column('route_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_uuid'], ['buses.uuid'], ),
    sa.ForeignKeyConstraint(['seat_uuid'], ['buses.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('bookings',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('luggage_uuid', sa.UUID(), nullable=True),
    sa.Column('route_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('selected_seat_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['luggage_uuid'], ['luggages.uuid'], ),
    sa.ForeignKeyConstraint(['route_uuid'], ['routes.uuid'], ),
    sa.ForeignKeyConstraint(['selected_seat_uuid'], ['selected_seats.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('selected_seats')
    op.drop_table('luggages')
    # ### end Alembic commands ###
