"""add booking_uuid to luggages

Revision ID: f375645bc299
Revises: 0aa15739a112
Create Date: 2026-08-20 11:57:49.794467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f375645bc299'
down_revision: Union[str, Sequence[str], None] = '0aa15739a112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_luggage_uuid_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'luggage_uuid')
    op.add_column('luggages', sa.Column('booking_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'luggages', 'bookings', ['booking_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'luggages', type_='foreignkey')
    op.drop_column('luggages', 'booking_uuid')
    op.add_column('bookings', sa.Column('luggage_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_luggage_uuid_fkey'), 'bookings', 'luggages', ['luggage_uuid'], ['uuid'])
    # ### end Alembic commands ###
